# -*- coding: utf-8 -*-
"""Haralick escala de grises.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Aqls6_PZGn-FhRoMKdLLnOpRg90Hcwvy
"""

!pip install mahotas

########## HARALICK ##########
from google.colab import drive
drive.mount('/content/drive')

########## imports ##########
import cv2
import numpy as np
from sklearn.svm import SVC
from sklearn.multiclass import OneVsRestClassifier
from sklearn.metrics import accuracy_score
import mahotas
import csv 

########## constantes ##########
PATH_BASE = "/content/drive/MyDrive/Colab Notebooks/Meastex_dividido/"
CSV_PRUEBA = "/content/drive/MyDrive/Colab Notebooks/resultados/haralick/vector_prueba_Meastex.csv"
CSV_ENTRENAMIENTO = "/content/drive/MyDrive/Colab Notebooks/resultados/haralick/vector_entrenamiento_Meastex.csv"
CSV_TITULOS = ["CLASE", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13"]

########## Funciones ##########
def leer_imagenes(txt): # txt: archivo.txt
  labels = np.array([])

  # Lectura de nombres de archivos de entrenamiento
  f = open(PATH_BASE + "000/" + txt,"r")
  lineas = f.readlines()

  imagenes = []
  for i in range(1, len(lineas)):
    nombreArchivo = lineas[i].split()[0]
    labels = np.append(labels, lineas[i].split()[1])
    path = PATH_BASE + "images/" + nombreArchivo
    img = cv2.imread(path, 0)
    imagenes.append(img)
  return imagenes, labels # retorna un array de imágenes y un array de nombre de clases

def extraer_haralick_features(imagenes):
  features_imagenes = []
  
  for imagen in imagenes:
    haralick = mahotas.features.haralick(imagen).mean(axis=0) # haralick devuelve un vector de 14 valores
    features_imagenes.append(haralick) 
  
  return features_imagenes

def entrenamiento(imagenes_entrenamiento, labels_entrenamiento):
  # Extracción de features de las imágenes de entrenamiento
  features_imagenes = extraer_haralick_features(imagenes_entrenamiento)

  # creación archivo de vector de caracteristicas
  with open(CSV_ENTRENAMIENTO,'w+') as f2:
    w = csv.writer(f2)
    titulos = CSV_TITULOS
    w.writerow(titulos)
    for i in range(len(features_imagenes)):
      fila = []
      fila.append(labels_entrenamiento[i])
      fila = fila + features_imagenes[i].tolist()
      w.writerow(fila)

  # Entrenar clasificador
  svm = OneVsRestClassifier(SVC(kernel = 'linear'))
  svm.fit(features_imagenes, labels_entrenamiento)
  
  return svm

def prueba(imagenes_prueba, labels_prueba, svm):
  # Extracción de features de las imágenes de prueba
  features_imagenes = extraer_haralick_features(imagenes_prueba)

  # creación archivo de vector de caracteristicas
  with open(CSV_PRUEBA,'w+') as f2:
    w = csv.writer(f2)
    titulos = CSV_TITULOS
    w.writerow(titulos)
    for i in range(len(features_imagenes)):
      fila = []
      fila.append(labels_prueba[i])
      fila = fila + features_imagenes[i].tolist()
      w.writerow(fila)

  # Predicciones utilizando SVM
  predicciones = svm.predict(features_imagenes)

  # Resultados
  exactitud = accuracy_score(labels_prueba, predicciones)
  print ('Exactitud: %0.3f' % exactitud)
  return exactitud

def main(imagenes_entrenamiento, labels_entrenamiento, imagenes_prueba, labels_prueba):
  print("Entrenamiento...")
  svm = entrenamiento(imagenes_entrenamiento, labels_entrenamiento)

  print("Prueba...")
  exactitud = prueba(imagenes_prueba, labels_prueba, svm)
  return exactitud

#Leer imágenes de entrenamiento (una sola vez)
print("Lectura de imágenes de entrenamiento....")
imagenes_entrenamiento, labels_entrenamiento =  leer_imagenes("train.txt")
print("Cantidad de imágenes de entrenamiento:",  len(imagenes_entrenamiento))

# Lectura de imágenes de prueba (una sola vez)
print("Lectura de imágenes de prueba....")
imagenes_prueba, labels_prueba =  leer_imagenes("test.txt")
print("Cantidad de imágenes de prueba:",  len(imagenes_prueba))

exactitud = main(imagenes_entrenamiento, labels_entrenamiento, imagenes_prueba, labels_prueba)

print(exactitud)